apiVersion: v1
kind: ConfigMap
metadata:
  name: kitchen-service-config
data:
  KITCHEN_DB_NAME: "restaurant_kitchen"
  KITCHEN_DB_URL: "jdbc:mysql://mysql:3306/restaurant_kitchen"
  PAYMENT_EVENTS_TOPIC: "payment.events"
  KITCHEN_EVENTS_TOPIC: "kitchen.events"
  KITCHEN_CONSUMER_GROUP: "kitchen-service"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KITCHEN_DEFAULT_QUEUE: "main-line"
