apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  ORDER_DB_NAME: "restaurant_order"
  ORDER_DB_URL: "jdbc:mysql://mysql:3306/restaurant_order"
  ORDER_EVENTS_TOPIC: "order.events"
  ORDER_COMMAND_TIMEOUT_MS: "5000"
