apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  INVENTORY_DB_NAME: "restaurant_inventory"
  INVENTORY_DB_URL: "jdbc:mysql://mysql:3306/restaurant_inventory"
  ORDER_EVENTS_TOPIC: "order.events"
  PAYMENT_EVENTS_TOPIC: "payment.events"
  INVENTORY_EVENTS_TOPIC: "inventory.events"
  INVENTORY_CONSUMER_GROUP: "inventory-service"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  INVENTORY_RESERVATION_TTL_SECONDS: "900"
