apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  NOTIFICATION_DB_NAME: "restaurant_notification"
  NOTIFICATION_DB_URL: "jdbc:mysql://mysql:3306/restaurant_notification"
  NOTIFICATION_EVENTS_TOPIC: "notification.events"
  NOTIFICATION_CHANNELS: "EMAIL,SMS,APP"
